SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS `task_manager` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `task_manager`;
CREATE TABLE IF NOT EXISTS `Task` (
`id` int NOT NULL,
`text` text NOT NULL,
`completed` boolean NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `Task` ADD PRIMARY KEY (`id`);
ALTER TABLE `Task` MODIFY `id` int NOT NULL AUTO_INCREMENT;
COMMIT;